[variables]
MISE_PYTHON_GITHUB_ATTESTATIONS = "false"

[phases.setup]
aptPkgs = [
  "tesseract-ocr",
  "tesseract-ocr-eng",
  "tesseract-ocr-ara",
  "libtesseract-dev",
  "libreoffice",
  "libreoffice-writer",
  "libreoffice-impress",
  "libreoffice-calc",
  "fonts-liberation",
  "fonts-dejavu",
  "fonts-noto",
  "fonts-noto-core",
  "fonts-noto-extra",
  "fonts-noto-ui-core",
  "fonts-arabeyes",
  "libgl1",
  "fontconfig"
]
